mongo_uri: "mongodb+srv://yashasvig_db_user:ENzdThDvVBAg6VUi@cluster0.ltykwqy.mongodb.net/?appName=ACM"
database: "acm"
collection: "telemetry"
port: "8080"
buffer_size: 10000
worker_count: 32
mode: "actual"