mongo_uri: "mongodb+srv://rajasekharp_db_user:vM4MT9yMtda7dCKj@nsh-test.klojnbb.mongodb.net/?appName=NSH-Test"
database: "cubesat"
collection: "telemetry"
port: "8080"
buffer_size: 10000
worker_count: 32
mode: "demo"
